config/routes.rb
Rails.application.routes.draw do
  resources :user_orders, :products, :product_categories

  resources :formulars do
    resources :formular_products
    resources :formular_orders
    resources :orders do
      resources :order_products, shallow: true
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    root to: 'users/sessions#new'
    get 'sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  match 'add_product_to_category', to: 'products#add_to_category', via: [:patch, :put]
  get 'home', to: 'formulars#index'
  get 'product/search', to: 'products#search'

  patch 'formulars/:formular_id/orders/:order_id/order_products/:id/increment_order_product_quantity',
    to: 'order_products#increment_quantity',
    as: 'increment_order_product_quantity'

  patch 'formulars/:formular_id/orders/:order_id/order_products/:id/decrement_order_product_quantity',
    to: 'order_products#decrement_quantity',
    as: 'decrement_order_product_quantity'

  get 'formular_order_modal/:id', to: 'formular_orders#modal', as: 'formular_order_modal'
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :authenticity_token, :commit, :_method, :order
  # Order & FormularOrder jointable
  has_many :formular_order, dependent: :delete_all
  has_many :submissions,
          foreign_key: 'order_id',
          class_name: 'FormularOrder'

  # Order & User jointable
  has_many :user_orders, dependent: :delete_all
  has_many :users, through: :user_orders

  # Order & Formular relationship
  belongs_to :formular
  accepts_nested_attributes_for :formular

  # Order & Product jointable
  has_many :order_products, dependent: :delete_all
  has_many :products, through: :order_products
  accepts_nested_attributes_for :order_products,
                                allow_destroy: true,
                                reject_if: proc { |attr| attr.order_product.product['name'].blank? }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include AccessControl

  before_action :set_formular,        only: [:show, :edit, :new, :create, :update]
  before_action :set_order,           only: [:show, :edit, :new, :update, :destroy]
  before_action :set_order_products,  only: [:edit, :update]
  before_action :build_order_product, only: [:show, :edit, :new]
  before_action :restrict_access_to_connected_users
  before_action :restrict_access_to_administrators_or_concerned_user, only: [:show, :edit]
  before_action :restrict_access_to_administrators, only: [:update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @formular          = Formular.find(order_params[:formular_id])
    @formular_products = @formular.products

    @order             = Order.new(formular_id: @formular.id)
    @order.order_products.build
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(formular_id: @formular.id,
                       barrack:     order_params.dig(:order, :barrack),
                       comment:     order_params.dig(:order, :comment))

    set_order_products

    respond_to do |format|
      if @order.save
        @formular_order = create_formular_order
        create_user_order

        OrderMailer.with(order: @order).new_order_email.deliver_now

        #format.js { flash.now[:success] = 'Soumission prise en compte' }
        format.html { redirect_to [@formular, @order], notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.js { flash.now[:error] = @order.errors.full_messages.first }
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to [@formular, @order], notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: [@formular, @order] }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = params.has_key?(:id) ? Order.find(params[:id]) : Order.new(order_params)
  end

  def set_formular
    @formular = Formular.find(order_params[:formular_id])
  end

  def set_order_products
    order_products_params = order_params.dig(:order, :order_products_attributes)

    if order_products_params
      order_products_params.each_value do |param|
        unless param['product_id'].blank?
          product = Product.find(param['product_id'])
          @order.order_products.build(product:  product,
                                      quantity: param['quantity'])
        end
      end
    end
  end

  def create_formular_order
    FormularOrder.create!(formular_id: @formular.id, order_id: @order.id)
  end

  def create_user_order
    UserOrder.create(user_id:           current_user.id,
                     order_id:          @order.id,
                     formular_order_id: @formular_order.id)
  end

  def build_order_product
    @builded_order_product = @order.order_products.build
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.permit(:formular_id,
                  :authenticity_token,
                  :commit,
                  :_method,
                  :id,
                  {
                    order_product:
                    [
                      :id
                    ],
                    order: 
                    [
                      :id,
                      :formular_id,
                      :barrack,
                      :comment,
                      :authenticity_token,
                      :commit,
                      order_products_attributes: OrderProduct.attribute_names.map(&:to_sym).push(:_destroy)
                    ]
                  }
                 )
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def build_table(formular, order, f)
    header = formular.has_product_categories ? render_categorized_header : render_default_header

#    if formular.has_product_categories && formular.products_have_dosage
#      body = render_categorized_body_with_dosage(formular, order, f)
#    elsif formular.has_product_categories && !formular.products_have_dosage
#      body = render_categorized_body(formular, order, f)
#    else
#      body = render_default_body(formular, order, f)
#    end

    #header + body
    header
  end

  def render_default_header
    render partial: 'orders/form_table_default_header'
  end

  def render_categorized_header
    render partial: 'orders/form_table_categorized_header'
  end

  def render_default_body(formular, order, f)
    render partial: 'orders/form_table_default_body', locals: { formular: formular, order: order, f: f }
  end

  def render_categorized_body(formular, order, f)
    render partial: 'orders/form_table_categorized_body', locals: { formular: formular, order: order, f: f }
  end

  def render_categorized_body_with_dosage(formular, order, f)
    render partial: 'orders/form_table_categorized_body_with_dosage', locals: { formular: formular, order: order, f: f }
  end
end

app/views/orders/_create_outline_sm_button.html.erb
<%= link_to new_formular_order_path(formular_id: formular.id) do %>
  <button class="btn btn-outline-primary btn-sm btn-block mb-2 float-right mx-1">Sélectionner</button>
<% end %>

app/views/orders/_form.html.erb
<h2 class="mb-5">Formulaire: <%= @formular.name %></h2>

<%= bootstrap_form_with(model: [formular, order], class: 'form-group', local: false) do |form| %>
  <%= form.alert_message 'Une erreur est survenue' %>

  <table class='table table-striped table-bordered'>
    <%= build_table(formular, order, form) %>
    <thead>
      <tr>
        <td>Libellée</td>
        <td class="pl-3">- / +</td>
        <td class="text-center">Quantité</td>
        <td></td>
      </tr>
    </thead>
    <tbody class='fields'>
      <%# TODO: set prefered barrack once user login stuff will be done %>
      <%= form.label 'Centre', class: 'font-weight-bold' %>
      <%= form.collection_select :barrack, User.barracks, :first, :first, { hide_label: true }, { class: 'mb-4' } %>

      <%= form.label 'Commentaires', class: 'font-weight-bold' %>
      <%= form.text_area :comment, hide_label: true, class: 'mb-4' %>

      <%= form.label 'Articles', class: 'font-weight-bold' %>
      <%= render partial: 'orders/order_product_row', collection: @order.order_products, as: :order_product %>

      <%# Row for builded order product (<select> tag) %>
      <%= form.fields_for :order_products, @builded_order_product do |order_product_fields| %>
        <%= render partial: 'orders/order_product', locals: { f:              order_product_fields,
                                                              order_products: @order.order_products } %>
      <% end %>
    </tbody>
  </table>
  <div class="row">
  <%= link_to_add_product_row('Ajouter un article', form, :order_products, class: 'mb-2') %>
  </div>
  <hr class="my-3">
  <%= form.submit class: 'btn btn-lg btn-block btn-success shadow mt-5' %>

<% end %>

app/views/orders/_form_table_categorized_header.html.erb
<thead>
  <tr>
    <td>Catégorie</td>
    <td>Libellé</td>
    <td class="text-center">Quantité</td>
    <td></td>
  </tr>
</thead>

app/views/orders/_form_table_categorized_header_with_dosage.html.erb
<thead>
  <tr>
    <td>Catégorie</td>
    <td>Libellé</td>
    <td class="text-center">Quantité</td>
    <td>Dosage</td>
    <td>Quantité minimum</td>
    <td>Quantité maximum</td>
    <td>Lot précédent</td>
    <td></td>
  </tr>
</thead>

app/views/orders/_form_table_default_header.html.erb
<thead>
  <tr>
    <td>Libellé</td>
    <td class="text-center">Quantité</td>
    <td></td>
  </tr>
</thead>

app/views/orders/_order_product.html.erb
<tr class='order_product_row'>
  <% if @formular.has_product_categories %>

    <td><%= f.collection_select(:category, ProductCategory.order(:name), :id, :name, { hide_label: true, prompt: 'Catégorie...' }, { class: 'order_product_row_category' } ) %></td>
    <td><%= f.grouped_collection_select(:product_id, ProductCategory.order(:name), :products, :name, :id, :name, { hide_label: true, prompt: 'Article...' }, { style: "width:300px", class: 'categorized_products order_product_row_product' }) %></td>
 
  <% else %>

    <td><%= f.collection_select(:product_id, @formular.products, :id, :name, { hide_label: true, prompt: 'Article...' }, { style: "width:300px" }) %></td>
  <% end %>
  <td><%= f.number_field :quantity, min: 1, size: 1, hide_label: true %></td>
  <td>
    <%= f.hidden_field :_destroy, as: :hidden, method: :delete %>
    <%= link_to '#', class: 'remove_order_product' do %>
      <i class="fas fa-trash-alt text-dark float-right mr-5 mt-2 shadow" title="Supprimer"></i>
  </td>
  <% end %>
</tr>
<script>$(function() { window.filterOrderProductCategories(); });</script>

app/views/orders/_order_product_row.html.erb
<% return if order_product.product.nil? %>

<tr id="order_product_<%= order_product.id.to_s %>">
  <td><%= order_product.product.name %></td>
  <td class="btn-group">
    <%= link_to '-', { action:     'decrement_quantity',
                       controller: 'order_products',
                       formular_id: @formular.id,
                       order_id:    @order.id,
                       id:          order_product.id },
                     { method: :patch,
                       remote: true,
                       class:  'btn btn-sm btn-secondary' }
    %>  
    <%= link_to '+', { action:    'increment_quantity',
                       controller:  'order_products', 
                       formular_id: @formular.id,
                       order_id:    @order.id,
                       id:          order_product.id },
                     { method: :patch,
                       remote: true,
                       class:  'btn btn-sm btn-primary' }
    %>
  </td>
  <td class="text-center"><%= order_product.quantity %></td>
  <td></td>
  <td>
    <%= link_to order_product, method: :delete, remote: true do %>
      <i class="fas fa-trash-alt text-dark float-right mr-5 mt-2 shadow" title="Supprimer"></i>
    <% end %>
  </td>
</tr>

app/views/orders/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <%= render partial: 'orders/form', locals: { order:         @order,
                                                 formular:      @formular,
                                                 order_product: @order_product } %>
  </div>
  <%= link_to 'Back', formular_orders_path %>
</div>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class='container'>
  <div class='jumbotron shadow'>
    <%= render partial: 'orders/form', locals: { order:         @order,
                                                 formular:      @formular,
                                                 order_product: @order_product } %>
  </div>
  <%= link_to 'Back', formulars_path %>
</div>

<%= javascript_pack_tag 'custom/order_products' if @formular.has_product_categories %>

app/views/orders/show.html.erb
<div class='container'>
  <div class='jumbotron shadow'>
    <%= render partial: 'orders/form', locals: { order:         @order,
                                                 formular:      @formular,
                                                 order_product: @order_product } %>
  </div>
  <%= link_to 'Back', formular_orders_path %>
</div>