config/routes.rb
Rails.application.routes.draw do
  resources :user_orders, :products, :product_categories

  resources :formulars do
    resources :formular_products
    resources :formular_orders
    resources :orders do
      resources :order_products, shallow: true
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    root to: 'users/sessions#new'
    get 'sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  match 'add_product_to_category', to: 'products#add_to_category', via: [:patch, :put]
  get 'home', to: 'formulars#index'
  get 'product/search', to: 'products#search'

  patch 'formulars/:formular_id/orders/:order_id/order_products/:id/increment_order_product_quantity',
    to: 'order_products#increment_quantity',
    as: 'increment_order_product_quantity'

  patch 'formulars/:formular_id/orders/:order_id/order_products/:id/decrement_order_product_quantity',
    to: 'order_products#decrement_quantity',
    as: 'decrement_order_product_quantity'

  get 'formular_order_modal/:id', to: 'formular_orders#modal', as: 'formular_order_modal'
end

app/models/formular_order.rb
class FormularOrder < ApplicationRecord
  belongs_to :formular
  belongs_to :order

  # OrderProduct relationship
  has_many :order_products, through: :order

  # User relationship
  has_one :user_order
  has_one :user, through: :user_order

  def submited_at
    created_at.strftime('%d/%m/%Y à %Hh%M')
  end

  def products
    order.products
  end

  def barrack
    order.barrack
  end

  def comment
    order.comment
  end
end

app/controllers/formular_orders_controller.rb
class FormularOrdersController < ApplicationController
  include AccessControl

  before_action :set_formular_order, only: [:show, :edit, :update, :destroy, :modal]
  before_action :restrict_access_to_administrators_or_concerned_user

  # GET /formular_orders
  # GET /formular_orders.json
  def index
    # Use this later for tracking users's submissions
    # @formular_orders = FormularOrder.all
    
    @formulars = Formular.all
  end

  # GET /formular_orders/1
  # GET /formular_orders/1.json
  def show
    @formular_order = FormularOrder.includes(:user).find(formular_order_params[:id])
    @formular       = Formular.includes(formular_products: :product).find(formular_order_params[:formular_id])
  end

  # GET /formular_orders/new
  def new
    @formular_order = FormularOrder.new
  end

  # GET /formular_orders/1/edit
  def edit
  end

  # POST /formular_orders
  # POST /formular_orders.json
  def create
    @formular_order = FormularOrder.new(formular_order_params)

    respond_to do |format|
      if @formular_order.save
        format.js { flash.now[:success] = 'Soumission enregistrée' }
        format.html { redirect_to @formular_order, notice: 'Formular order was successfully created.' }
        format.json { render :show, status: :created, location: @formular_order }
      else
        fomart.js { flash.now[:danger] = @formular_order.errors.full_messages.first }
        format.html { render :new }
        format.json { render json: @formular_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formular_orders/1
  # PATCH/PUT /formular_orders/1.json
  def update
    respond_to do |format|
      if @formular_order.update(formular_order_params)
        format.js { flash.now[:notice] = 'CHECK FormularOrder CONTROLLER' }
        format.html { redirect_to @formular_order, notice: 'Formular order was successfully updated.' }
        format.json { render :show, status: :ok, location: @formular_order }
      else
        format.js { flash.now[:danger] = @formular_order.errors.full_messages.first }
        format.html { render :edit }
        format.json { render json: @formular_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formular_orders/1
  # DELETE /formular_orders/1.json
  def destroy
    @formular_order.destroy
    respond_to do |format|
      format.js { flash.now[:warning] = 'CHECK FormularOrder CONTROLLER' }
      format.html { redirect_to formular_orders_url, notice: 'Formular order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def modal
    @formular_order = FormularOrder.includes(order_products: :product).find(formular_order_params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formular_order
      @formular_order = FormularOrder.find(params[:id])
    end

    def set_formular
      @formular = Formular.find(params[:formular_id])
    end

    # Only allow a list of trusted parameters through.
    def formular_order_params
      params.permit(:formular_id, :order_id, :has_product_categories, :id)
    end
end

app/helpers/formular_orders_helper.rb
module FormularOrdersHelper
end

app/views/formular_orders/_create_outline_sm_button.html.erb
<%= link_to new_formular_formular_order_path(formular_id: formular.id) do %>
  <button class="btn btn-outline-primary btn-sm mb-3 float-right mx-1">Sélectionner</button>
<% end %>

app/views/formular_orders/_form.html.erb
<%= form_with(model: [:formular, formular_order]) do |form| %>
  <% if formular_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formular_order.errors.count, "error") %> prohibited this formular_order from being saved:</h2>

      <ul>
        <% formular_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :formular_id %>
    <%= form.text_field :formular_id %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formular_orders/_product_table.html.erb
<table class='table table-striped table-bordered shadow'>
  <thead>
    <tr>
      <td>Libellé</td>
      <td>Quantité</td>
    </tr>
  </thead>
  <tbody>
    <% products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/formular_orders/_submission.html.erb
<p><strong>Centre:</strong> <%= submission.barrack %></p>

<p><strong>Commentaires:</strong> <%= submission.comment %></p>

<p><strong>Soumis le:</strong> <%= submission.submited_at %></p>

<p><strong>Articles:</strong></p>
<%= render partial: 'formular_orders/product_table', locals: { products: submission.order_products } %>

app/views/formular_orders/_submission_modal.html.erb
<div class='modal fade' id='modal-<%= submission.id %>' tabindex='-1' role='dialog' aria-labelledby='aze' aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'>

      <div class='modal-header'>
        <h5 class='modal-title' id='aze'>
          <%= submission.submited_at %>
        </h5>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </div>

      <div class='modal-body'>
        <%= render partial: 'formular_orders/submission', locals: { submission: submission} %>
      </div>

      <div class='modal-footer'>
        <button type='button' class='btn btn-secondary' data-dismiss='modal'>Fermer</button>
      </div>
    </div>
  </div>
</div>

app/views/formular_orders/_submission_row.html.erb
<tr>
  <td><%= submission.user.username rescue 'TODO set username' %></td>
  <td><%= submission.barrack %></td>
  <td><%= submission.submited_at %></td>
  <td>
    <%= link_to formular_order_modal_path(submission), remote: true do %>
      <button type='button' class='btn btn-sm btn-outline-primary' data-toggle='modal' data-target='#modal-<%= submission.id %>'>Détails</button>
    <% end %>
  </td>
</tr>

app/views/formular_orders/_submission_table.html.erb
<div class="table-responsive">
  <table class="table table-striped text-center">
    <thead>
      <tr>
        <th scope="col">Utilisateur</th>
        <th scope="col">Centre</th>
        <th scope="col">Date</th>
        <th scope="col">Consulter</th>
      </tr>
    </thead>
    <tbody>
      <% submissions.each do |submission| %>
        <%= render partial: 'formular_orders/submission_row', locals: { submission: submission } %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/formular_orders/edit.html.erb
<h1>Editing Formular Order</h1>

<%= render 'form', formular_order: @formular_order %>

<%= link_to 'Show', @formular_order %> |
<%= link_to 'Back', formular_orders_path %>

app/views/formular_orders/index.html.erb
<p id="notice"><%= notice %></p>

<div class='container'>
  <h1>Formulaires</h1>
  <br>

  <div class='ml-3'>
    <%= render partial: 'formulars/cards_formulars', locals: { formulars: @formulars } %>
    <hr>
  </div>
</div>

app/views/formular_orders/modal.js.erb
$('body').append('<%= j render partial: "formular_orders/submission_modal", locals: { submission: @formular_order} %>');

$('#modal-<%= @formular_order.id %>').modal('show');

app/views/formular_orders/new.html.erb
<h1>New Formular Order</h1>

<%= render 'form', formular_order: @formular_order %>

<%= link_to 'Back', formular_formular_orders_path %>

app/views/formular_orders/show.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="container shadow">

      <%= render partial: 'formular_orders/submission', locals: { submission: @formular_order } %>

    </div>
  </div>

  <%= link_to 'Retour', formular_path(@formular) %>
</div>