config/routes.rb
Rails.application.routes.draw do
  resources :user_orders, :products, :product_categories

  resources :formulars do
    resources :formular_products
    resources :formular_orders
    resources :orders do
      resources :order_products, shallow: true
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    root to: 'users/sessions#new'
    get 'sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  match 'add_product_to_category', to: 'products#add_to_category', via: [:patch, :put]
  get 'home', to: 'formulars#index'
  get 'product/search', to: 'products#search'

  patch 'formulars/:formular_id/orders/:order_id/order_products/:id/increment_order_product_quantity',
    to: 'order_products#increment_quantity',
    as: 'increment_order_product_quantity'

  patch 'formulars/:formular_id/orders/:order_id/order_products/:id/decrement_order_product_quantity',
    to: 'order_products#decrement_quantity',
    as: 'decrement_order_product_quantity'

  get 'formular_order_modal/:id', to: 'formular_orders#modal', as: 'formular_order_modal'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-5">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to 'Formulaires', formulars_path, class: 'nav-link' %>
      </li>
    <% end %>

    </ul>
    <ul class="navbar-nav ml-auto">

      <% if admin? %>
        <li class="nav-item dropdown mr-4">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Administration
          </a>
          <div class="dropdown-menu", aria-labelledby="navbarDropdown">
            <div class="dropdown-header">FORMULAIRES</div>
            <%= link_to 'Consulter', formulars_path, class: 'dropdown-item' %>
            <%= link_to 'Créer', new_formular_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <div class="dropdown-header">CATEGORIES</div>
            <%= link_to 'Consulter', product_categories_path, class: 'dropdown-item' %>
            <%= link_to 'Créer', new_product_category_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <div class="dropdown-header">ARTICLES</div>
            <%= link_to 'Consulter', products_path, class: 'dropdown-item' %>
            <%= link_to 'Créer', new_product_path, class: 'dropdown-item' %>
          </div>
        </li>
      <% end %>

        <li class="nav-item mr-2">
          <% if user_signed_in? %>
            <%= link_to 'Se déconnecter', destroy_user_session_path, class: 'nav-link' %>
          <% else %>
            <%= link_to 'Se connecter', sign_in_path, class: 'nav-link' %>
          <% end %>
        </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormularPharmacy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div id='flash' class='flex-column'>
      <%= render 'shared/flash' %>
    </div>
    <%= yield %>
  </body>
</html>